/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32h743xx.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint32_t u32Ticks = 0U;
uint8_t u8Update = 0U;

int main(void)
{
    /* Loop forever */
	RCC->AHB4ENR |= RCC_AHB4ENR_GPIOBEN;
	while(RCC_AHB4ENR_GPIOBEN != (RCC->AHB4ENR & RCC_AHB4ENR_GPIOBEN));

	GPIOB->MODER = (0x1U << GPIO_MODER_MODE0_Pos) |
			(0x1U << GPIO_MODER_MODE7_Pos) |
			(0x1U << GPIO_MODER_MODE14_Pos);
	GPIOB->OTYPER = (0x0U << GPIO_OTYPER_OT0_Pos) |
			(0x0U << GPIO_OTYPER_OT7_Pos) |
			(0x0U << GPIO_OTYPER_OT14_Pos);
	GPIOB->PUPDR = (0x0U << GPIO_PUPDR_PUPD0_Pos) |
			(0x0U << GPIO_PUPDR_PUPD7_Pos) |
			(0x0U << GPIO_PUPDR_PUPD14_Pos);
	GPIOB->OSPEEDR = (0x0U << GPIO_OSPEEDR_OSPEED0_Pos) |
			(0x0U << GPIO_OSPEEDR_OSPEED7_Pos) |
			(0x0U << GPIO_OSPEEDR_OSPEED14_Pos);
	GPIOB->ODR = (0x0U << GPIO_ODR_OD0_Pos) |
			(0x0U << GPIO_ODR_OD7_Pos) |
			(0x0U << GPIO_ODR_OD14_Pos);

	SysTick_Config(0xFFFFF0U);

	while(1U)
	{
		if(1U == u8Update)
		{
			u8Update = 0U;
			if(0U == (u32Ticks & 0x3U))
			{
				GPIOB->ODR ^= (0x1U << GPIO_ODR_OD0_Pos);
			}
			if(0U == (u32Ticks & 0x7U))
			{
				GPIOB->ODR ^= (0x1U << GPIO_ODR_OD7_Pos);
			}
			if(0U == (u32Ticks & 0xFU))
			{
				GPIOB->ODR ^= (0x1U << GPIO_ODR_OD14_Pos);
			}
		}
	}
}

void SysTick_Handler(void)
{
	u32Ticks++;
	u8Update = 1U;
}
